<?php
  $path_to_style="product/style.css";
  $path_to_layout="product/layout.css";
  $text_file="whoweare.txt";
  include('templates/header.php');
  include('templates/import_text.php');
?>
  </body>
</html>
